#!/bin/bash

#DOCKER_REGISTRY_URI=_DOCKER_REGISTRY_URI_
#DOCKER_REGISTRY_USER=_DOCKER_REGISTRY_USER_
#DOCKER_REGISTRY_PASS=_DOCKER_REGISTRY_PASS_

if [[ -z "$DOCKER_REGISTRY_URI" ]] || [[ -z "$DOCKER_REGISTRY_USER" ]] || [[ -z "$DOCKER_REGISTRY_PASS" ]]
then
  echo "[!] Please, provide the following environment variables:"
  echo '    - $DOCKER_REGISTRY_URI'
  echo '    - $DOCKER_REGISTRY_USER'
  echo '    - $DOCKER_REGISTRY_PASS'
  exit 1
fi

docker login -u $DOCKER_REGISTRY_USER --password-stdin $DOCKER_REGISTRY_URI << EOF
$DOCKER_REGISTRY_PASS
EOF
